package com.mygdx.game.screens;
import com.badlogic.gdx.*; import com.badlogic.gdx.graphics.*; import com.badlogic.gdx.graphics.g2d.*; import com.badlogic.gdx.math.*; import com.badlogic.gdx.utils.ScreenUtils; import com.mygdx.game.*; import com.mygdx.game.objects.*; import com.mygdx.game.views.*; import java.util.*;
public class GameScreen extends ScreenAdapter {private final MyGdxGame game;private final ArrayList<TrashObject> trash=new ArrayList<TrashObject>();private final ArrayList<BulletObject> bullets=new ArrayList<BulletObject>();private final ArrayList<BossBulletObject> bossBullets=new ArrayList<BossBulletObject>();private BossObject boss;private final GameSession session=new GameSession();private final MovingBackgroundView background;private final ImageView topBlackout,pauseIcon;private final TextView scoreText,pauseText,endText;private final LifeView lives;private final ButtonView home,continueButton;private final RecordsListView records;
 public GameScreen(MyGdxGame g){game=g;game.world.setContactListener(new ContactManager(g.audioManager));background=new MovingBackgroundView(GameResources.BACKGROUND_IMG_PATH);topBlackout=new ImageView(0,1180,GameResources.BLACKOUT_TOP_IMG_PATH);pauseIcon=new ImageView(635,1190,GameResources.PAUSE_IMG_PATH);scoreText=new TextView(g.commonWhiteFont,35,1210,"Score: 0");lives=new LifeView(300,1210);pauseText=new TextView(g.largeWhiteFont,285,900,"Pause");endText=new TextView(g.largeWhiteFont,245,970,"Last records");home=new ButtonView(270,760,180,65,g.commonBlackFont,GameResources.BUTTON_SHORT_BG_IMG_PATH,"Home");continueButton=new ButtonView(350,760,180,65,g.commonBlackFont,GameResources.BUTTON_SHORT_BG_IMG_PATH,"Continue");records=new RecordsListView(g.commonWhiteFont,800);}
 @Override public void show(){restartGame();}
 private ShipObject ship;
 private void restartGame(){for(TrashObject t:trash){game.world.destroyBody(t.getBody());t.dispose();}for(BulletObject b:bullets){game.world.destroyBody(b.getBody());b.dispose();}for(BossBulletObject b:bossBullets){game.world.destroyBody(b.getBody());b.dispose();}trash.clear();bullets.clear();bossBullets.clear();if(boss!=null){game.world.destroyBody(boss.getBody());boss.dispose();boss=null;}if(ship!=null){game.world.destroyBody(ship.getBody());ship.dispose();}ship=new ShipObject(GameSettings.SCREEN_WIDTH/2,150,150,150,GameResources.SHIP_IMG_PATH,game.world);session.startGame();lives.setLeftLives(ship.getLives());scoreText.setText("Score: 0");}
 private void input(){if(Gdx.input.isTouched()){game.touch=game.camera.unproject(new Vector3(Gdx.input.getX(),Gdx.input.getY(),0));if(session.state==GameState.PLAYING){if(pauseIcon.isHit(game.touch.x,game.touch.y))session.state=GameState.PAUSED;else ship.move(game.touch);}else if(session.state==GameState.PAUSED){if(home.isHit(game.touch.x,game.touch.y))game.setScreen(game.menuScreen);else if(continueButton.isHit(game.touch.x,game.touch.y))session.state=GameState.PLAYING;}else if(home.isHit(game.touch.x,game.touch.y))game.setScreen(game.menuScreen);}}
 private void update(){if(session.shouldSpawnTrash())trash.add(new TrashObject(80,80,GameResources.TRASH_IMG_PATH,game.world));if(boss==null&&session.shouldSpawnEnemy())boss=new BossObject(GameSettings.SCREEN_WIDTH/2,GameSettings.SCREEN_HEIGHT+100,game.world);if(ship.needToShoot()){bullets.add(new BulletObject(ship.getX(),ship.getY()+75,GameSettings.BULLET_WIDTH,GameSettings.BULLET_HEIGHT,GameResources.BULLET_IMG_PATH,game.world));ship.markShot();game.audioManager.playShoot();}if(boss!=null&&boss.isReadyToShoot()){bossBullets.add(new BossBulletObject(boss.getX(),boss.getY()-110,game.world));boss.markShot();game.audioManager.playShoot();}game.stepWorld();for(TrashObject t:trash)t.move();if(boss!=null)boss.move();for(BossBulletObject b:bossBullets)b.move();for(int i=trash.size()-1;i>=0;i--){TrashObject t=trash.get(i);if(t.hasToBeDestroyed()){game.world.destroyBody(t.getBody());t.dispose();trash.remove(i);}}for(int i=bullets.size()-1;i>=0;i--){BulletObject b=bullets.get(i);if(b.hasToBeDestroyed()){game.world.destroyBody(b.getBody());b.dispose();bullets.remove(i);if(b.wasHit())session.score++;}}for(int i=bossBullets.size()-1;i>=0;i--){BossBulletObject b=bossBullets.get(i);if(!b.isInFrame()){game.world.destroyBody(b.getBody());b.dispose();bossBullets.remove(i);}}if(boss!=null&&boss.hasToBeDestroyed()){game.world.destroyBody(boss.getBody());boss.dispose();boss=null;session.score+=10;}lives.setLeftLives(ship.getLives());if(!ship.isAlive()){session.state=GameState.ENDED;java.util.List<Integer> r=MemoryManager.loadTableRecords();r.add(session.score);MemoryManager.saveTableRecords(r);records.setRecords(MemoryManager.loadTableRecords());}scoreText.setText("Score: "+session.score);}
 private void draw(){game.camera.update();game.batch.setProjectionMatrix(game.camera.combined);ScreenUtils.clear(Color.CLEAR);game.batch.begin();background.draw(game.batch);for(TrashObject t:trash)t.draw(game.batch);for(BulletObject b:bullets)b.draw(game.batch);for(BossBulletObject b:bossBullets)b.draw(game.batch);if(boss!=null)boss.draw(game.batch);ship.draw(game.batch);topBlackout.draw(game.batch);scoreText.draw(game.batch);lives.draw(game.batch);if(session.state==GameState.PLAYING){pauseIcon.draw(game.batch);}else if(session.state==GameState.PAUSED){pauseText.draw(game.batch);home.draw(game.batch);continueButton.draw(game.batch);}else{endText.draw(game.batch);records.draw(game.batch);home.draw(game.batch);}game.batch.end();}
 @Override public void render(float d){input();if(session.state==GameState.PLAYING)update();draw();}
 @Override public void dispose(){background.dispose();topBlackout.dispose();pauseIcon.dispose();scoreText.dispose();lives.dispose();pauseText.dispose();endText.dispose();home.dispose();continueButton.dispose();records.dispose();if(ship!=null)ship.dispose();if(boss!=null)boss.dispose();}
}
