package com.mygdx.game.screens;
import com.badlogic.gdx.*; import com.badlogic.gdx.graphics.*; import com.badlogic.gdx.math.Vector3; import com.badlogic.gdx.utils.ScreenUtils; import com.mygdx.game.*; import com.mygdx.game.views.*;
public class SettingsScreen extends ScreenAdapter {private final MyGdxGame game;private final ImageView background;private final TextView title,music,sound,clear;private final ButtonView returnButton;
 public SettingsScreen(MyGdxGame g){game=g;background=new ImageView(0,0,GameResources.BACKGROUND_IMG_PATH);title=new TextView(g.largeWhiteFont,260,960,"Settings");music=new TextView(g.commonWhiteFont,245,790,"");sound=new TextView(g.commonWhiteFont,245,750,"");clear=new TextView(g.commonWhiteFont,245,710,"clear records");returnButton=new ButtonView(285,540,150,70,g.commonBlackFont,GameResources.BUTTON_SHORT_BG_IMG_PATH,"return");updateText();}
 private void updateText(){music.setText("music: "+(game.audioManager.isMusicOn?"on":"off"));sound.setText("sound: "+(game.audioManager.isSoundOn?"on":"off"));}
 private boolean hit(float y){return game.touch.x>=235&&game.touch.x<=535&&game.touch.y>=y&&game.touch.y<=y+45;} private void input(){if(!Gdx.input.justTouched())return;game.touch=game.camera.unproject(new Vector3(Gdx.input.getX(),Gdx.input.getY(),0));if(hit(775)){game.audioManager.isMusicOn=!game.audioManager.isMusicOn;MemoryManager.saveMusicSettings(game.audioManager.isMusicOn);game.audioManager.updateMusicFlag();updateText();}else if(hit(735)){game.audioManager.isSoundOn=!game.audioManager.isSoundOn;MemoryManager.saveSoundSettings(game.audioManager.isSoundOn);updateText();}else if(hit(695)){MemoryManager.saveTableRecords(new java.util.ArrayList<Integer>());}else if(returnButton.isHit(game.touch.x,game.touch.y))game.setScreen(game.menuScreen);}
 @Override public void render(float d){input();game.camera.update();game.batch.setProjectionMatrix(game.camera.combined);ScreenUtils.clear(Color.CLEAR);game.batch.begin();background.draw(game.batch);title.draw(game.batch);music.draw(game.batch);sound.draw(game.batch);clear.draw(game.batch);returnButton.draw(game.batch);game.batch.end();}
 @Override public void dispose(){background.dispose();title.dispose();music.dispose();sound.dispose();clear.dispose();returnButton.dispose();}
}
